Added a bunch of improvements to the script: * -p flag to indicate creating directories to mirror repo structure * only create local master/develop branches * initialize repo for Gitflow * handle both ssh and http style urls      git flow clone git@united:path/to/repo      git flow clone https://github.com/nvie/gitflow.git

diff --git a/git-flow-clone b/git-flow-clone
--- a/git-flow-clone
+++ b/git-flow-clone
@@ -1,36 +1,50 @@
 #!/bin/sh
 
+USAGE='Clone a git repo with support for the gitflow branching model.
+    usage: git flow clone [options] [--] <repo> [<dir>]
+  options: -p Create intermediate directories as required.'
 
-INSTRUCTIONS="Clone a git repo with support for the gitflow branching model."
-USAGE="usage: git flow clone [options] [--] <repo> [<dir>]"
-INSTALL="Install with:\n  git-flow-clone install"
+# Something went wrong
+function fail { echo "$USAGE" >&2; exit 1; }
 
-function fail { echo $USAGE >&2; exit 1; }
-function instruct { echo $INSTRUCTIONS; echo $USAGE; exit 0; }
+# Extracts a DIR and REPO when given a URL
+function parse_url {
+  web='https?://[^/]+/'
+  ssh='[^:]+:'
+  path=`echo "$1" | sed -E "s,($web|$ssh),,"`
+  DIR=`dirname "$path"`
+  REPO=`basename "$path" | sed -E "s/.git$//"`
+}
 
-if [ "git-flow-clone" = `basename "$0"` ]; then
-  if [ "$1" = "install" ]; then
-    gitflow_home=$(dirname $(type git-flow | awk '{ print $NF }'))
-    cp "$0" "$gitflow_home" || sudo cp "$0" "$gitflow_home"
-    echo "git-flow-clone installed"
-    instruct
+# Clones a repo and performs Gitflow setup
+function clone_repo {
+  git clone $1 -b master || fail
+  cd "$REPO"
+  if (git checkout develop 2> /dev/null); then
+    git flow init -d
+  else
+    echo "converting a non-Gitflow repo into a Gitflow repo"
+    git flow init -d
+    git push -u origin develop
   fi
-  echo "$INSTRUCTIONS \n\n$INSTALL" >&2
-  exit 1
+}
+
+# Missing <repo> arg
+if [ $# -eq 0 ]; then fail; fi
+
+if [ $1 = '-p' ]; then
+  # Copy directory structre
+  parse_url $2
+  mkdir -p "$DIR" || fail
+  cd "$DIR"
+  clone_repo $2
+  echo "Gitflow repo cloned to ${DIR}/${REPO}"
+else
+  # Clone in place
+  parse_url $1
+  clone_repo $1
+  echo "Gitflow repo cloned to ${REPO}"
 fi
 
-for last_arg; do true; done
-DIR=`echo "$last_arg" | sed -e 's/[^:]*://'`
-
-git clone $@ 2> /dev/null || fail
-cd "$DIR"
-
-non_tracking_branches=`git branch -r | awk '/origin/ { print $NF }' \
-    | grep -v 'origin/master'`
-for branch in $non_tracking_branches; do
-  local_name=`echo "$branch" | sed -e 's/origin\///'`
-  git branch -t "$local_name" "$branch"
-done
-git checkout develop
-
+# exit so we don't continue continue up the git call stack
 exit 0
